modLoader="javafml"
loaderVersion="[47,)"
license="Custom license"

[[mods]]
modId="trslimex"
version="1.0.0"
displayName="trslim Extra"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
updateJSONURL="https://github.com/NoteSwiper/trslim-extra/raw/master/update.json"
authors="user, MCreator"

[[dependencies.trslimex]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




